[versions]
kotlin = "2.1.21"
android-application = "8.9.1"
android-library = "8.9.1"
compose-compiler = "1.5.12"
hilt = "2.56"
hiltNavigationCompose = "1.2.0"
ksp = "2.1.21-2.0.2"
androidx-core = "1.16.0"
appcompat = "1.7.1"
material = "1.12.0"
compose-ui = "1.8.3"
compose-material3 = "1.3.2"
activity-compose = "1.10.1"
lifecycle-viewmodel-compose = "2.9.1"
coroutines = "1.10.2"
room = "2.7.2"
moshi = "1.15.1"
auto-service = "1.1.1"
annotation = "1.9.1"
kotlinx-coroutines-core = "1.8.0"
jetbrains-ompose = "1.8.2"
junit = "4.13.2"
accompanist = "0.30.1"
materialIconsExtended = "1.6.1"

# coil
coil = "2.4.0"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrains-ompose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-library" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }

# Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }

accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }

androidx-compose-materialIconsExtended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
